"""
Django settings for HospitalRecommendation project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zs^l8#-t)s4sw=!on+%_4_@alp3#vxnqwerj9ud8@ybfnxkpit'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Hospital',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HospitalRecommendation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HospitalRecommendation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'hospital', 
    'HOST': 'localhost',
    'PORT': '3306',
    'USER': 'admin',
    'PASSWORD': 'admin',
}
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = [                    #Static Files haru ko direcotry dekhako... i.e hamile static folder banako xau.. so tyo folder ko naam 'static' xa ... yo static folder ma sabbai static files haru xa
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom Django auth settings

AUTH_USER_MODEL = 'Hospital.User'

LOGIN_URL = 'login' #This one is used when we use decorators like @login_required in views.py. This gives the path to redirect to login page if user isn't login


CRISPY_TEMPLATE_PACK='bootstrap4' #For designing django inbuilt form (like signup forms) with crispy framework.

# For Connecting Bootstrap alerts to Django message tags. This messages comes from viwes.py and we show this alert message in templates
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
 }


 #SMTP Configuration                                          # yo tala ko chai Password Reset mail send garna ko lagi chaine kura haru ho

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'               #yo line ma j xa tei nai lekna parxa
EMAIL_HOST = 'smtp.gmail.com'                                               #gmail ko id vayera gmail.com gareko
EMAIL_PORT = 587                                                            #Since we are using TLS, so we use EMAIL_PORT = 587
EMAIL_USE_TLS = True                                                        # TLS lai TRUE garne
EMAIL_HOST_USER = 'internsem9860@gmail.com'                                #jun gmail batw reset email pathaune ho tyo email ID lekhinxa
EMAIL_HOST_PASSWORD = 'MyInternSem2020@9860'

# To Create Fixtures
FIXTURE_DIRS = (
   '/home/dipendra/Django/Hospital/Hospital_Recommendation/Hospital/fixtures/',
)
