# Generated by Django 2.2 on 2020-09-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20200828_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
