# Generated by Django 2.2 on 2020-10-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20200926_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='Hospital.Hospital'),
        ),
    ]
